version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Copy files to EC2
          command: |
            sudo apt-get update
            sudo apt-get install -y rsync
            rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/khang-server-key.pem" ./ ubuntu@ec2-13-54-220-223.ap-southeast-2.compute.amazonaws.com:/home/ubuntu/app
      - run:
          name: Start Application on EC2
          command: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/khang-server-key.pem ubuntu@ec2-13-54-220-223.ap-southeast-2.compute.amazonaws.com "cd /home/ubuntu/app && npm install && pm2 start index.js"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build